export async function fixRichTextCells(
  cells: Array<{ ref: string; field: "requirement" | "copyText" | "style"; raw: string }>
): Promise<Record<string, string>> {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey || cells.length === 0) {
    return {};
  }

  const model = process.env.OPENROUTER_MODEL || "qwen/qwen3.6-plus";

  const prompt = buildTextFixPrompt(cells);

  try {
    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    if (!response.ok) {
      console.error("[ai-text-fixer] OpenRouter request failed:", await response.text());
      return {};
    }

    const json = await response.json();
    const content = json?.choices?.[0]?.message?.content;
    if (!content) return {};

    try {
      const parsed = JSON.parse(content);
      return parsed.fixed ?? {};
    } catch {
      console.error("[ai-text-fixer] Failed to parse AI response as JSON:", content);
      return {};
    }
  } catch (err) {
    console.error("[ai-text-fixer] Error calling OpenRouter:", err);
    return {};
  }
}

function buildTextFixPrompt(
  cells: Array<{ ref: string; field: "requirement" | "copyText" | "style"; raw: string }>
): string {
  return `You are a data cleaning assistant. A spreadsheet parser extracted cell values that contain corrupted rich-text metadata mixed with actual text content. Your job is to identify the real text in each cell and return ONLY the cleaned text.

The corrupted text was generated by WPS/AutoStore which embeds font names, colors, and sizes as text runs alongside the actual content. Examples of corruption:
- "11FFFF0000微软雅黑134扫清炎热，聚会也凉爽&#10;11微软雅黑1341" → "扫清炎热，聚会也凉爽"
- "11FFFF0000宋体134新品上市&#10;11宋体1341" → "新品上市"
- "22FFFF0000黑体146CLDNEWTEXT122黑体1462" → "CLDNEWTEXT"

For each cell below, extract ONLY the meaningful text content. Ignore all font metadata, color codes, size numbers, HTML entities, and formatting noise.

Cells to clean:
${JSON.stringify(cells.map((c) => ({ ref: c.ref, field: c.field, raw: c.raw })), null, 2)}

Return a JSON object mapping each cell reference to its cleaned text:
{
  "C3": "Cleaned requirement text here",
  "F5": "Cleaned copy text here",
  ...
}

Rules:
- Preserve Chinese, English, numbers, and punctuation that are actual content
- Remove font names (微软雅黑, 宋体, 黑体, etc.)
- Remove hex color codes (FFFF0000, etc.)
- Remove font size numbers mixed into text
- Remove HTML entities like &#10;
- Remove repeated patterns like "11...134"
- Keep text concise - do not summarize or rephrase
- If a cell is already clean, keep it as-is
- If text is completely corrupted/unrecoverable, return empty string
- Return valid JSON only, no markdown fences`;
}
