"use client";

import Link from "next/link";
import { ArrowLeft, Calculator, CircleAlert, Loader2, Sparkles } from "lucide-react";
import { useState } from "react";
import { TIKTOK_REFERENCE } from "@/lib/tiktok-pricing";
import type { TikTokPricingCalculation, TikTokPricingCountry, TikTokPricingMarketInput, TikTokPricingRequest } from "@/lib/types";

const countryOrder: TikTokPricingCountry[] = ["SG", "MY", "TH", "VN", "PH"];
const initialForm = { productCostRmb: "20", packagingCostRmb: "2", weightG: "392", buyerPayPercent: "40", targetMarginPercent: "20", affiliateRate: "0" };

function defaultMarket(country: TikTokPricingCountry): TikTokPricingMarketInput {
  const reference = TIKTOK_REFERENCE.countries[country];
  return { country, currency: reference.currency, exchangeRateRmbPerLocal: reference.exchangeRateRmbPerLocal, commissionRate: reference.commissionRate, transactionRate: reference.transactionRate, supportFee: 0, region: country === "MY" ? "west" : country === "PH" ? "manila" : country === "TH" ? "zone-a" : country === "VN" ? "zone-a" : "default", channel: country === "VN" ? "Economy" : "Standard", includeLocalDeliveryCost: false };
}
function numberValue(value: string) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
function money(value: number, currency: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 2 }).format(value); }
function Field(props: { label: string; value: string; onChange: (value: string) => void; suffix?: string; type?: "number" | "text" }) {
  return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wide text-zinc-500">{props.label}</span><div className="flex items-center rounded-md border border-white/10 bg-black/25 px-3 focus-within:border-lime-300/60"><input type={props.type ?? "number"} inputMode={props.type === "text" ? "text" : "decimal"} value={props.value} onChange={(event) => props.onChange(event.target.value)} className="w-full bg-transparent py-2.5 text-sm text-white outline-none [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none" />{props.suffix ? <span className="ml-2 font-mono text-xs text-zinc-600">{props.suffix}</span> : null}</div></label>;
}

function countryLabel(country: TikTokPricingCountry) { return `${country} · ${TIKTOK_REFERENCE.countries[country].name}`; }
function regionOptions(country: TikTokPricingCountry): Array<[TikTokPricingMarketInput["region"], string]> {
  if (country === "MY") return [["west", "西马"], ["east", "东马"]];
  if (country === "TH") return [["zone-a", "Zone A"], ["zone-b", "Zone B"], ["zone-c", "Zone C"]];
  if (country === "VN") return [["zone-a", "Zone A"], ["zone-b", "Zone B"], ["zone-c", "Zone C"], ["zone-d", "Zone D"]];
  if (country === "PH") return [["manila", "马尼拉"], ["other", "其他区"]];
  return [["default", "全境"]];
}

export default function TikTokPricingPage() {
  const [form, setForm] = useState(initialForm);
  const [market, setMarket] = useState(defaultMarket("SG"));
  const [result, setResult] = useState<TikTokPricingCalculation | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function set(key: keyof typeof form, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  function chooseCountry(country: TikTokPricingCountry) { setMarket(defaultMarket(country)); setResult(null); }
  async function submit() {
    setLoading(true); setError(null);
    try {
      const payload: TikTokPricingRequest = { productCostRmb: numberValue(form.productCostRmb), packagingCostRmb: numberValue(form.packagingCostRmb), weightG: numberValue(form.weightG), buyerPayPercent: numberValue(form.buyerPayPercent), targetMarginPercent: numberValue(form.targetMarginPercent), affiliateRate: numberValue(form.affiliateRate), market };
      const response = await fetch("/api/tiktok-pricing/recommend", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
      const data = await response.json() as { calculation?: TikTokPricingCalculation; error?: string };
      if (!response.ok || !data.calculation) throw new Error(data.error ?? "无法生成定价建议。");
      setResult(data.calculation);
    } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "无法生成定价建议。"); }
    finally { setLoading(false); }
  }

  const country = market.country;
  return <main className="min-h-screen bg-[#10100f] text-zinc-100"><div className="mx-auto w-full max-w-6xl px-4 py-6 md:px-8">
    <header className="flex flex-col gap-4 border-b border-white/10 pb-5 sm:flex-row sm:items-center sm:justify-between"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-lime-100 hover:text-lime-200"><ArrowLeft size={16} />返回首页</Link><span className="font-mono text-xs text-zinc-600">TikTok Shop · Pricing</span></header>
    <section className="py-8"><p className="mb-3 inline-flex items-center gap-2 rounded-md border border-lime-300/20 bg-lime-300/10 px-3 py-1 text-xs font-semibold text-lime-100"><Calculator size={14} /> Pricing workstation</p><h1 className="text-3xl font-semibold tracking-tight text-white sm:text-5xl">TikTok 定价建议</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">先选择目标国家，再填入成本、重量、折扣和费率。公式负责算清楚底线，大模型负责把结果翻译成简单的经营建议。</p></section>
    <div className="flex flex-col gap-5">
      <section className="space-y-5"><div className="rounded-lg border border-lime-300/30 bg-lime-300/[0.06] p-5"><h2 className="font-semibold text-white">1. 选择目标国家</h2><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{countryOrder.map((item) => <button key={item} type="button" onClick={() => chooseCountry(item)} className={`rounded-md border px-2 py-3 text-left transition ${country === item ? "border-lime-300 bg-lime-300 text-zinc-950" : "border-white/10 bg-black/20 text-zinc-400 hover:border-lime-300/40"}`}><span className="block font-mono text-sm font-semibold">{item}</span><span className="mt-1 block text-[11px]">{TIKTOK_REFERENCE.countries[item].name}</span></button>)}</div></div>
      <div className="rounded-lg border border-white/10 bg-white/[0.04] p-5"><h2 className="font-semibold text-white">2. 商品成本与折扣</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="商品成本" value={form.productCostRmb} onChange={(v) => set("productCostRmb", v)} suffix="RMB" /><Field label="包装 / 国内段" value={form.packagingCostRmb} onChange={(v) => set("packagingCostRmb", v)} suffix="RMB" /><Field label="包裹实重" value={form.weightG} onChange={(v) => set("weightG", v)} suffix="g" /><Field label="买家支付比例（4折=40%）" value={form.buyerPayPercent} onChange={(v) => set("buyerPayPercent", v)} suffix="%" /></div><p className="mt-4 text-[11px] leading-5 text-zinc-600">运费价卡按包裹实重计费，重量会向上取整到下一个 10g 档位。</p></div>
      <div className="rounded-lg border border-white/10 bg-white/[0.04] p-5"><h2 className="font-semibold text-white">3. 价格参数</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="目标利润 / 成本" value={form.targetMarginPercent} onChange={(v) => set("targetMarginPercent", v)} suffix="%" /><Field label="达人佣金（不用填 0）" value={form.affiliateRate} onChange={(v) => set("affiliateRate", v)} suffix="%" /></div><p className="mt-4 text-[11px] leading-5 text-zinc-600">平台佣金和交易费在下方国家设置中填写，直接以你从 Seller Center 查到的实际费率为准。</p></div>
      <div className="rounded-lg border border-white/10 bg-white/[0.04] p-5"><div className="mb-4"><h2 className="font-semibold text-white">4. {countryLabel(country)} 运费与费率</h2><p className="mt-1 text-xs text-zinc-500">新价卡按包裹实重、起重价和每 10g 续重计算；以下默认值均可修改。</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="人民币 / 当地币" value={String(market.exchangeRateRmbPerLocal)} onChange={(v) => setMarket({ ...market, exchangeRateRmbPerLocal: numberValue(v) })} /><Field label="平台佣金" value={String(market.commissionRate)} onChange={(v) => setMarket({ ...market, commissionRate: numberValue(v) })} suffix="%" /><Field label="交易费" value={String(market.transactionRate)} onChange={(v) => setMarket({ ...market, transactionRate: numberValue(v) })} suffix="%" /><Field label="每单支持费" value={String(market.supportFee)} onChange={(v) => setMarket({ ...market, supportFee: numberValue(v) })} suffix={market.currency} /><label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wide text-zinc-500">地区 / 区域</span><select value={market.region} onChange={(e) => setMarket({ ...market, region: e.target.value as TikTokPricingMarketInput["region"] })} className="w-full rounded-md border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none">{regionOptions(country).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wide text-zinc-500">物流渠道</span><select value={market.channel} onChange={(e) => setMarket({ ...market, channel: e.target.value as TikTokPricingMarketInput["channel"] })} className="w-full rounded-md border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none"><option>Standard</option><option>Economy</option></select></label><label className="flex items-center gap-2 text-sm text-zinc-300 sm:col-span-2"><input type="checkbox" checked={market.includeLocalDeliveryCost} onChange={(e) => setMarket({ ...market, includeLocalDeliveryCost: e.target.checked })} className="accent-lime-300" />我也承担买家下单时支付的当地派送费</label><div className="sm:col-span-2"><Field label="自定义卖家运费（可选，填了就覆盖新价卡）" value={market.logisticsOverride === undefined ? "" : String(market.logisticsOverride)} onChange={(v) => setMarket({ ...market, logisticsOverride: v.trim() === "" ? undefined : numberValue(v) })} suffix={market.currency} /></div></div></div>
      <button type="button" disabled={loading} onClick={submit} className="inline-flex w-full items-center justify-center gap-2 rounded-md bg-lime-300 px-4 py-3 text-sm font-semibold text-zinc-950 transition hover:bg-lime-200 disabled:cursor-not-allowed disabled:opacity-50">{loading ? <><Loader2 size={16} className="animate-spin" />正在计算...</> : <><Sparkles size={16} />生成售价建议</>}</button>{error ? <p className="rounded-md border border-red-400/20 bg-red-400/10 px-3 py-2 text-sm text-red-200">{error}</p> : null}</section>
      <section className="space-y-5">{result ? <div className="rounded-lg border border-lime-300/30 bg-lime-300/[0.06] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-white">计算结果 · {countryLabel(country)}</h2><span className="font-mono text-[10px] text-lime-100">FORMULA FIRST</span></div><div className="mt-4 space-y-3">{result.results.map((item) => <div key={item.country} className="rounded-md border border-white/10 bg-black/20 p-4"><div className="flex items-baseline justify-between"><div><span className="font-mono text-lg font-semibold text-lime-100">{item.country}</span><span className="ml-2 text-xs text-zinc-500">计费重 {item.chargeableWeightG}g · 运费 {money(item.logistics, item.currency)}</span></div><span className="font-mono text-xl font-semibold text-white">{money(item.suggestedPrice, item.currency)}</span></div><p className="mt-2 text-[11px] text-zinc-500">{item.freightBasis}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><div><p className="text-zinc-600">折后成交</p><p className="mt-1 font-mono text-zinc-200">{money(item.discountedPrice, item.currency)}</p></div><div><p className="text-zinc-600">保本挂牌</p><p className="mt-1 font-mono text-zinc-200">{money(item.breakEvenPrice, item.currency)}</p></div><div><p className="text-zinc-600">目标价</p><p className="mt-1 font-mono text-zinc-200">{money(item.targetPrice, item.currency)}</p></div><div><p className="text-zinc-600">预计利润</p><p className="mt-1 font-mono text-lime-100">{money(item.estimatedProfit, item.currency)}</p></div></div><div className="mt-3 border-t border-white/10 pt-3 text-[11px] leading-5 text-zinc-500">佣金 + 交易费 + 达人：{(item.totalFeeRate * 100).toFixed(2)}% · 费用：{money(item.feesAtSuggestedPrice, item.currency)}</div>{item.warnings.map((warning) => <p key={warning} className="mt-2 flex gap-1.5 text-[11px] leading-5 text-amber-200/80"><CircleAlert size={13} className="mt-0.5 shrink-0" />{warning}</p>)}</div>)}</div></div> : <div className="flex min-h-[280px] flex-col items-center justify-center rounded-lg border border-dashed border-white/10 bg-white/[0.02] p-8 text-center"><Calculator size={28} className="text-zinc-700" /><h2 className="mt-4 font-semibold text-zinc-300">结果会显示在这里</h2><p className="mt-2 max-w-sm text-sm leading-6 text-zinc-600">先选国家并填写参数。建议价会同时展示保本线、折后成交价和预计利润。</p></div>}</section>
    </div><p className="mt-6 text-[11px] leading-5 text-zinc-600">运费参考：{TIKTOK_REFERENCE.workbookSource}（各国家工作表含生效日期）。官方费率仍需在 Seller Center / Seller Academy 复核；公式未包含广告、退货损耗、税费、活动服务费和买家运费补贴。</p><p className="mt-2 text-[11px] leading-5 text-zinc-600">官方入口：<a className="text-lime-100 hover:underline" href={TIKTOK_REFERENCE.officialSources.sgCommission} target="_blank" rel="noreferrer">SG 佣金</a> · <a className="text-lime-100 hover:underline" href={TIKTOK_REFERENCE.officialSources.sgTransaction} target="_blank" rel="noreferrer">SG 交易费</a> · <a className="text-lime-100 hover:underline" href={TIKTOK_REFERENCE.officialSources.myFees} target="_blank" rel="noreferrer">MY 佣金/卖家费用</a> · <a className="text-lime-100 hover:underline" href={TIKTOK_REFERENCE.officialSources.myTransaction} target="_blank" rel="noreferrer">MY 交易费</a> · <a className="text-lime-100 hover:underline" href={TIKTOK_REFERENCE.officialLogisticsUrl} target="_blank" rel="noreferrer">物流</a></p>
  </div></main>;
}
